-- CFC Hædersbevisninger (historiske) — kombineret fra alle kørsler af scrape_honors.py
-- Kør med: wrangler d1 execute forzachang-db --remote --file=database/seed_honors.sql

-- ── Årets fighter ──────────────────────────────────────────────────────────────
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-f-2007', p.id, ht.id, 2007, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Peter Hesselholt' AND ht.key = 'fighter' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-f-2011', p.id, ht.id, 2011, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Morten Ladegaard' AND ht.key = 'fighter' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-f-2012', p.id, ht.id, 2012, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Casper Sørrig' AND ht.key = 'fighter' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-f-2013', p.id, ht.id, 2013, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Mikael Strandbygaard' AND ht.key = 'fighter' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-f-2014', p.id, ht.id, 2014, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Peter Hesselholt' AND ht.key = 'fighter' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-f-2015', p.id, ht.id, 2015, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Kristian Nøhr' AND ht.key = 'fighter' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-f-2016', p.id, ht.id, 2016, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Mikael Strandbygaard' AND ht.key = 'fighter' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-f-2017', p.id, ht.id, 2017, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Morten Sørensen' AND ht.key = 'fighter' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-f-2018', p.id, ht.id, 2018, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Henrik Stein' AND ht.key = 'fighter' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-f-2019', p.id, ht.id, 2019, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Mathias Elisberg' AND ht.key = 'fighter' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-f-2021', p.id, ht.id, 2021, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Mikael Strandbygaard' AND ht.key = 'fighter' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-f-2022', p.id, ht.id, 2022, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Henrik Kjærsgaard' AND ht.key = 'fighter' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-f-2023', p.id, ht.id, 2023, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Morten Ladegaard' AND ht.key = 'fighter' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-f-2024', p.id, ht.id, 2024, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Henrik Kjærsgaard' AND ht.key = 'fighter' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
-- Mangler: 2008, 2009, 2010, 2020 — ikke fundet på forzachang.dk

-- ── Årets spiller ──────────────────────────────────────────────────────────────
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-s-2007', p.id, ht.id, 2007, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Christian Næsby' AND ht.key = 'spiller' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-s-2008', p.id, ht.id, 2008, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Ivar Rosendal' AND ht.key = 'spiller' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-s-2010', p.id, ht.id, 2010, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Christian Næsby' AND ht.key = 'spiller' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-s-2011', p.id, ht.id, 2011, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Jacob Jørgensen' AND ht.key = 'spiller' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-s-2012', p.id, ht.id, 2012, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Morten Larsen' AND ht.key = 'spiller' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-s-2013', p.id, ht.id, 2013, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Jacob Jørgensen' AND ht.key = 'spiller' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-s-2014', p.id, ht.id, 2014, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Mikael Strandbygaard' AND ht.key = 'spiller' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-s-2015', p.id, ht.id, 2015, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Peter Hesselholt' AND ht.key = 'spiller' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-s-2016', p.id, ht.id, 2016, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Morten Sørensen' AND ht.key = 'spiller' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-s-2017', p.id, ht.id, 2017, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Jeppe Dyrberg' AND ht.key = 'spiller' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-s-2018', p.id, ht.id, 2018, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Jeppe Dyrberg' AND ht.key = 'spiller' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-s-2020', p.id, ht.id, 2020, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Rasmus Nissen' AND ht.key = 'spiller' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-s-2023', p.id, ht.id, 2023, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Rasmus Nissen' AND ht.key = 'spiller' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
-- Mangler: 2009, 2019, 2021, 2022, 2024 — ikke fundet på forzachang.dk

-- ── Årets kammerat ─────────────────────────────────────────────────────────────
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-k-2008', p.id, ht.id, 2008, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Kenneth Christensen' AND ht.key = 'kammerat' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-k-2010', p.id, ht.id, 2010, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Peter Hesselholt' AND ht.key = 'kammerat' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-k-2011', p.id, ht.id, 2011, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Christian Næsby' AND ht.key = 'kammerat' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-k-2012', p.id, ht.id, 2012, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Morten Buus' AND ht.key = 'kammerat' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-k-2013', p.id, ht.id, 2013, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Christian Næsby' AND ht.key = 'kammerat' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-k-2014', p.id, ht.id, 2014, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Jens Erik Zebis' AND ht.key = 'kammerat' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-k-2015', p.id, ht.id, 2015, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Christian Næsby' AND ht.key = 'kammerat' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-k-2017', p.id, ht.id, 2017, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Jens Erik Zebis' AND ht.key = 'kammerat' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-k-2018', p.id, ht.id, 2018, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Christian Vendelbo' AND ht.key = 'kammerat' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-k-2019', p.id, ht.id, 2019, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Christian Næsby' AND ht.key = 'kammerat' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-k-2020', p.id, ht.id, 2020, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Henrik Stein' AND ht.key = 'kammerat' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-k-2021', p.id, ht.id, 2021, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Henrik Stein' AND ht.key = 'kammerat' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-k-2022', p.id, ht.id, 2022, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Mathias Elisberg' AND ht.key = 'kammerat' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-k-2023', p.id, ht.id, 2023, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Mikael Strandbygaard' AND ht.key = 'kammerat' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
INSERT INTO player_honors (id, player_id, honor_type_id, season, awarded_by, created_at) SELECT 'ah-k-2024', p.id, ht.id, 2024, NULL, datetime('now') FROM players p, honor_types ht WHERE p.name = 'Henrik Stein' AND ht.key = 'kammerat' ON CONFLICT(player_id, honor_type_id, season) DO NOTHING;
-- Mangler: 2007, 2009, 2016 — ikke fundet på forzachang.dk
